"""
Planck SDK - Quantum Circuit representation
"""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class QuantumCircuit:
    """
    Represents a quantum circuit generated by Planck.
    
    Attributes:
        qasm: OpenQASM 2.0 code for the circuit
        qubits: Number of qubits in the circuit
        depth: Circuit depth (layers of gates)
        gate_count: Total number of gates
        gates: List of gate operations
        algorithm: Algorithm used to generate the circuit
        recommended_shots: ML-recommended number of shots
    """
    qasm: str
    qubits: int
    depth: int
    gate_count: int
    gates: List[str] = field(default_factory=list)
    algorithm: str = "unknown"
    recommended_shots: int = 1024
    
    def to_dict(self) -> dict:
        """Convert circuit to dictionary representation."""
        return {
            "qasm": self.qasm,
            "qubits": self.qubits,
            "depth": self.depth,
            "gate_count": self.gate_count,
            "gates": self.gates,
            "algorithm": self.algorithm,
            "recommended_shots": self.recommended_shots,
        }
    
    def save(self, filepath: str) -> None:
        """
        Save QASM code to a file.
        
        Args:
            filepath: Path to save the file
        """
        with open(filepath, "w") as f:
            f.write(self.qasm)
    
    @property
    def clean_qasm(self) -> str:
        """Return QASM code without header comments."""
        lines = self.qasm.split("\n")
        clean_lines = [l for l in lines if not l.startswith("//")]
        return "\n".join(clean_lines)
    
    def __repr__(self) -> str:
        return (
            f"QuantumCircuit(qubits={self.qubits}, "
            f"depth={self.depth}, gates={self.gate_count}, "
            f"algorithm='{self.algorithm}')"
        )
